### PR TITLE
Add fat arrow clarification

### PR DESCRIPTION
**Pull request by rdallasgray**
I felt I really didn't explain this very well yesterday. This is better, and is also an invitation to comment on and edit it so we can nail it down.

Hopefully we can start to own and use this guide a bit more?

### CODE REVIEW

**Comment by smeyfroi** [comment]
This is good… should have read it properly ages ago.  :-/

**Comment by smeyfroi** [comment]
OK, I think we should whip thru this whole doc on a Tuesday L&L: we need to sit together and agree on some of this stuff... Shouldn't take more than 15 minutes probably, but it's worth doing? @lawrence-berry @neil-morrison44 @dunckr @rdallasgray

**Comment by rdallasgray** [comment]
Sure.

**Comment by dunckr** [comment]
Good idea @smeyfroi 
It might be worth using some previous PRs where there was style changes for reference

**Comment by smeyfroi** [comment]
Sure: keep some up your sleeve. Hopefully we can get through it/agree it very quickly, but there are a couple of areas that I want to pick a fight and I’m sure I won’t be the only one. So put em up. Outside in the carpark. Now. Just you and me.

**Comment by rdallasgray** [comment]
[hides]

**Comment by dunckr** [comment]
Can move onto this the following [week](http://ricardo.cc/2011/06/02/10-CoffeeScript-One-Liners-to-Impress-Your-Friends.html)

**Comment by rdallasgray** [comment]
Are we OK to merge this, anyway?

**Comment by smeyfroi** [comment]
Go on then. Just this once.

**Pull request merged**
